# Generated by Django 4.0 on 2023-09-13 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a city name', max_length=168, verbose_name='Сity name')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='city_country', to='countries.country')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'ordering': ['name'],
            },
        ),
    ]
