# Generated by Django 4.0 on 2023-09-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_currency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='currency',
            options={'ordering': ['name'], 'verbose_name_plural': 'Currencies'},
        ),
    ]
