# Generated by Django 4.0 on 2023-09-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_alter_currency_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a ciry description', max_length=3000, null=True, verbose_name='City description'),
        ),
        migrations.AddField(
            model_name='city',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='city_photos'),
        ),
        migrations.AddField(
            model_name='country',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a country description', max_length=3000, null=True, verbose_name='Country description'),
        ),
        migrations.AddField(
            model_name='country',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='country_photos'),
        ),
    ]
