# Generated by Django 4.0 on 2023-09-14 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_city_description_city_photo_country_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='country',
            name='photo',
        ),
        migrations.CreateModel(
            name='CountryPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='country_photos')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_photos_country', to='countries.country')),
            ],
            options={
                'verbose_name_plural': 'Photos of countries',
                'ordering': ['country'],
            },
        ),
        migrations.CreateModel(
            name='CityPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='city_photos')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_photos_city', to='countries.city')),
            ],
            options={
                'verbose_name_plural': 'Photos of cities',
                'ordering': ['city'],
            },
        ),
    ]
