# Generated by Django 4.0 on 2023-09-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0006_remove_city_photo_remove_country_photo_countryphotos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='country_photos'),
        ),
    ]
