# Generated by Django 4.0 on 2023-09-15 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0007_country_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='attractions',
            field=models.TextField(blank=True, help_text='Enter a country attractions', max_length=3000, null=True, verbose_name='Country attractions'),
        ),
    ]
