# Generated by Django 4.0 on 2023-09-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0008_country_attractions'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='city_photos'),
        ),
    ]
