# Generated by Django 4.0 on 2023-09-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0009_city_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='attractions',
            field=models.TextField(blank=True, help_text='Enter a city attractions', max_length=3000, null=True, verbose_name='City attractions'),
        ),
    ]
